### PR TITLE
:rocket: break apart dynamic requires for webpack

### PR DESCRIPTION
**Pull request by drewwells**
webpack statically analyzes require statements. When expressions
are found, it generates a dynamic require context based on values
it can find. However, passing a dynamic array to require is out
of scope for this simple analysis. Reworking this method makes
it possible for webpack to read and properly bundle the i18n
files for it.

For more information, see https://webpack.github.io/docs/context.html

### CODE REVIEW

**Comment by tomasAlabes** [comment]
Although this can't be merged as is, it's true that oj/ojscore is not parseable by webpack. If the `oj.Config.setLocale` can be changed to be webpack compatible it would be helpful for the people who use webpack as the module bundler.
:)

**Comment by drewwells** [comment]
Of course no expectations that this would be merged. It's more of documentation of a possible change.

**Comment by tomasAlabes** [comment]
@drewwells you can try using a plugin I created for this. I haven't used it in production yet but it worked in an isolated case. It's the [oj-plugin](https://github.com/tomasAlabes/oj-plugin).
Let me know if you have any feedback!

**Comment by drewwells** [comment]
@tomasAlabes  That's pretty interesting approach. Does the webpack amd plugin handle the require() call at runtime?

**Comment by tomasAlabes** [comment]
@drewwells The final bundle will contain the plain require call, the `oj.Config.setLocale` function is left as is. So at runtime rjs needs to be loaded to handle it.

**Comment by peppertech** [comment]
We will be adding WebPack support later this year.  We will not use the method you have provided in your pull-request.  We appreciate your involvement, and willingness to help make JET better for everyone.  Follow us on Twitter @oraclejet for news about the release of Webpack support.

**Pull request closed without merging**
